server:
  port: 8972 

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:6033/encore
    #url: jdbc:mariadb://database:3306/encore
    username: todo_user
    password: todo_passwd
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: mappers/*.xml
