INSERT INTO ENCORE_TODO_TBL(SUBJECT, BODY, COMPLETED)
VALUES('test1', 'test1', 0);

INSERT INTO ENCORE_TODO_TBL(SUBJECT, BODY, COMPLETED)
VALUES('test2', 'test2', 0);

INSERT INTO ENCORE_TODO_TBL(SUBJECT, BODY, COMPLETED)
VALUES('test3', 'test3', 0);